"""spec #2 — family-agnostic candidate ranker: fixtures.

Covers the spec §Fixtures matrix:
  (a) bionic-first ranking for ``rand`` + the glibc/ansi mismatch summaries +
      an explicit ``why_top``  (the TC2 proof-point).
  (b) a SECOND, synthetic symbol with ≥2 families ranks with NO scorer change —
      proves the scorer is family-agnostic (registered via register_family_hint).
  (c) NO_CANDIDATE — observed behaviour belongs to no registered family.
  (d) INSUFFICIENT_OBSERVATION — too few returns to discriminate; names the need.

The (a) observations are COMPUTED from #1's own bionic model (reuse, not a magic
vector): ``eval_sequence(seed=1, 8, low8)``. This anchors the ranker proof-point
to the same reference impl #1 already pins.
"""

from __future__ import annotations

from engine.extern_model import (
    CandidateRanking,
    ModelFamilyHint,
    RANK_INSUFFICIENT_OBSERVATION,
    RANK_NO_CANDIDATE,
    RANK_RANKED,
    family_hints_for,
    rank_model_candidates,
    register_family_hint,
    resolve_extern_model,
)


def _bionic_low8(seed: int, count: int) -> list[int]:
    m = resolve_extern_model("rand", runtime_tags={"libc_family": "bionic"})
    return m.eval_sequence(seed=seed, count=count, project="low8")


# --------------------------------------------------------------------------- #
# (a) PROOF-POINT (TC2): rand + seed + first 8 returns ⇒ bionic ranked first,
#     with glibc / ansi mismatch summaries and an explicit why_top.
# --------------------------------------------------------------------------- #
def test_proof_point_rand_ranks_bionic_first_with_mismatches():
    observed = _bionic_low8(1, 8)
    r = rank_model_candidates("rand", observed_seed=1, observed_returns=observed)

    assert isinstance(r, CandidateRanking)
    assert r.verdict == RANK_RANKED
    # #1 row is bionic, full match, promoted to observed_match evidence.
    top = r.top
    assert top is not None
    assert top.family == "bionic"
    assert top.model_id == "bionic-random-type3"
    assert top.score == 1.0
    assert top.match and "8/8" in top.match
    assert top.evidence_level == "observed_match"

    # The rival families are present with structured mismatch summaries.
    others = {c.family: c for c in r.ranked[1:]}
    assert {"ansi-lcg", "glibc-lcg"} <= set(others)
    for fam in ("ansi-lcg", "glibc-lcg"):
        c = others[fam]
        assert c.score < 1.0
        assert not c.match
        assert c.mismatch and "diverges at return #" in c.mismatch

    # why_top is an EXPLICIT reason (cites the match count + a runner-up), not a
    # bare name.
    assert "bionic" in r.why_top
    assert "8/8" in r.why_top or "matched" in r.why_top
    assert "runner-up" in r.why_top


def test_proof_point_glibc_random_type3_collapsed_as_behaviour_alias():
    # bionic random() and glibc random() are the SAME BSD TYPE_3 table (kept as
    # two #1 registry entries only to prove tag DISPATCH). The ranker collapses
    # behavioural aliases so they never manufacture a false tie.
    fams = {h.model_id for h in family_hints_for("rand")}
    assert "bionic-random-type3" in fams
    assert "glibc-random-type3" not in fams  # collapsed into bionic
    assert {"glibc-rand-type0", "ansi-lcg"} <= fams


def test_ranking_is_advisory_not_a_closed_finding():
    observed = _bionic_low8(1, 8)
    r = rank_model_candidates("rand", observed_seed=1, observed_returns=observed)
    assert "advisory" in r.detail
    assert "verifier" in r.detail  # never auto-promoted to a closed finding


# --------------------------------------------------------------------------- #
# (b) GENERALITY: a second, synthetic symbol with ≥2 families ranks with NO
#     scorer code change — registered purely as DATA.
# --------------------------------------------------------------------------- #
def _toy_even(seed: int, count: int) -> list[int]:
    # stream: seed, seed+2, seed+4, ... (mod 256)
    return [(seed + 2 * i) & 0xFF for i in range(count)]


def _toy_double(seed: int, count: int) -> list[int]:
    # stream: seed, 2*seed, 4*seed, ... (mod 256) — diverges from _toy_even fast
    v = seed & 0xFF
    out = []
    for _ in range(count):
        out.append(v)
        v = (v * 2) & 0xFF
    return out


def test_second_symbol_ranks_with_no_scorer_change():
    sym = "toy_gen"
    register_family_hint(ModelFamilyHint(
        symbol=sym, family="even-step", model_id="toy-even",
        eval=_toy_even, project="low8", version="toy-1"))
    register_family_hint(ModelFamilyHint(
        symbol=sym, family="doubler", model_id="toy-double",
        eval=_toy_double, project="low8", version="toy-2"))

    # Observed behaviour generated by the even-step family for seed=7.
    observed = _toy_even(7, 8)
    r = rank_model_candidates(sym, observed_seed=7, observed_returns=observed)

    assert r.verdict == RANK_RANKED
    assert r.top is not None
    assert r.top.family == "even-step"
    assert r.top.score == 1.0
    # The other family is scored and shown to diverge — same scorer, no edits.
    doubler = next(c for c in r.ranked if c.family == "doubler")
    assert doubler.mismatch and "diverges" in doubler.mismatch
    assert "even-step" in r.why_top


# --------------------------------------------------------------------------- #
# (c) NO_CANDIDATE — observed behaviour matches no registered family.
# --------------------------------------------------------------------------- #
def test_no_candidate_when_no_family_matches():
    # A stream that matches none of rand's families even at return #1.
    bogus = [0, 1, 2, 3, 4, 5, 6, 7]
    r = rank_model_candidates("rand", observed_seed=1, observed_returns=bogus)
    assert r.verdict == RANK_NO_CANDIDATE
    # Structured: per-family divergence is reported, not a silent empty result.
    assert "matched even return #1" in r.detail
    assert r.ranked  # rows are still present (each scored 0 with a mismatch)
    assert all(c.matched == 0 for c in r.ranked)


def test_no_candidate_when_symbol_has_no_registered_family():
    r = rank_model_candidates(
        "totally_unknown_sym", observed_seed=1, observed_returns=[1, 2, 3])
    assert r.verdict == RANK_NO_CANDIDATE
    assert "no candidate family registered" in r.detail
    assert r.ranked == ()


# --------------------------------------------------------------------------- #
# (d) INSUFFICIENT_OBSERVATION — too few returns; names how many it needs.
# --------------------------------------------------------------------------- #
def test_insufficient_observation_zero_returns_names_need():
    r = rank_model_candidates("rand", observed_seed=1, observed_returns=[])
    assert r.verdict == RANK_INSUFFICIENT_OBSERVATION
    assert r.needed_observations >= 1
    assert "need" in r.detail.lower()


def test_insufficient_observation_partial_match_not_committable():
    # First 2 returns match bionic, then a deliberately wrong 3rd value: best
    # family matches a partial prefix only → not committable, asks for more.
    observed = _bionic_low8(1, 2) + [999]
    r = rank_model_candidates("rand", observed_seed=1, observed_returns=observed)
    assert r.verdict == RANK_INSUFFICIENT_OBSERVATION
    assert r.needed_observations >= 3
    assert "not yet committable" in r.detail or "not a full-prefix" in r.detail
    # The partial match is still surfaced (advisory), never silently dropped.
    assert r.top is not None
    assert r.top.family == "bionic"
    assert r.top.matched == 2


def test_insufficient_observation_on_full_match_tie():
    # Two synthetic families that agree on the first 3 bytes then diverge. With a
    # 3-byte observation both fully match → a tie the ranker refuses to break.
    sym = "tie_gen"
    register_family_hint(ModelFamilyHint(
        symbol=sym, family="alpha", model_id="tie-alpha",
        eval=lambda s, n: [(s + i) & 0xFF if i < 3 else (s + i) & 0xFF for i in range(n)],
        project="low8"))
    register_family_hint(ModelFamilyHint(
        symbol=sym, family="beta", model_id="tie-beta",
        eval=lambda s, n: [(s + i) & 0xFF if i < 3 else (s + i + 100) & 0xFF for i in range(n)],
        project="low8"))
    # Observe only the shared 3-byte prefix.
    observed = [(5 + i) & 0xFF for i in range(3)]
    r = rank_model_candidates(sym, observed_seed=5, observed_returns=observed)
    assert r.verdict == RANK_INSUFFICIENT_OBSERVATION
    assert r.needed_observations >= 4
    assert "too short to" in r.detail
